# Generated by Django 5.1.6 on 2025-03-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_product_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürünler', 'verbose_name_plural': 'Ürünler'},
        ),
    ]
