# Generated by Django 5.1.6 on 2025-03-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0006_alter_creditcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
