# Generated by Django 5.1.6 on 2025-03-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0008_alter_useraddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='full_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
